version: '3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: djangoProject
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "22:22"

  vm:
    build:
      context: vm
      dockerfile: Dockerfile
    ports:
      - "9000:9000"