#!/bin/bash

shm_permissions=$(ls -ld /run/shm | cut -c 2-10)
if [ $shm_permissions == "rwxrwxrwx" ]; then
echo "Warning: The /run/shm directory is readable and writable for running programs by users!";
fi

